### ISSUE TITLE
Agora on Android

### ISSUE THREAD

**Issue by sbeleidy** [PEERbots/PEERbots#5]
The current Android Playstore version isn't working with Agora due to the 64bit compilation requirement. 

We asked in the Agora forum about this and they mentioned following this: 
<img width="1177" alt="Screen Shot 2021-10-20 at 8 44 39 AM" src="https://user-images.githubusercontent.com/1388511/138935804-2ae45e79-df5d-493f-8e2f-14af161e2c49.png">

I'm using this issue to track progress on this. 

@johnchoi313 can you update me here on when you've tried this and we can follow up in the forum if that still doesn't work?

**Comment by johnchoi313** [comment]
Agora replaced with Pubnub, works and compiles and complies with Google Play Store requirements
